url: "https://www.roqu.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Roquio" # the name of your site, e.g. ACME Corp.

description:
lang: "fr_FR"
email: "contact@roqu.io"

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

sass:
#  sass_dir: _sass
  style: compressed


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
   - .sass-cache/
   - .jekyll-cache/
   - Gemfile
   - Gemfile.lock
   - LICENSE
   - README.md
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
